/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryType = IDL.Variant({
  'bulkOrder' : IDL.Null,
  'general' : IDL.Null,
  'dealership' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiriesByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
  'getInquiriesByType' : IDL.Func([InquiryType], [IDL.Vec(Inquiry)], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'getLatestInquiries' : IDL.Func([IDL.Nat], [IDL.Vec(Inquiry)], ['query']),
  'searchInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryType = IDL.Variant({
    'bulkOrder' : IDL.Null,
    'general' : IDL.Null,
    'dealership' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiriesByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
    'getInquiriesByType' : IDL.Func(
        [InquiryType],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'getLatestInquiries' : IDL.Func([IDL.Nat], [IDL.Vec(Inquiry)], ['query']),
    'searchInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };